language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
      - openjdk-8-jdk
notifications:
  email: false
sudo: required
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - chmod +x gradlew
  - java -version
  - javac -version
jdk:
  - oraclejdk8
  - openjdk8
