notifications:
  email: false
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
      script:
        - java -version
        - javac -version
        - ./gradlew test
    - language: java
      dist: trusty
      jdk: openjdk8
      script:
        - java -version
        - javac -version
        - ./gradlew test
      addons:
        apt:
          packages:
            - openjdk-8-jdk