notifications:
  email: false
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - java -version
        - javac -version
    - language: java
      dist: trusty
      jdk: openjdk8
      script:
        - java -version
        - javac -version
