language: generic
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
      - openjdk-8-jdk
notifications:
  email: false
env:
  - BUILD_TYPE=ORACLE_JDK_8
  - BUILD_TYPE=OPEN_JDK_8
script:
  - ./build.sh
