notifications:
  email: false
matrix:
  include:
    #OracleJDK 8
    - language: java
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_script:
        - java -version
        - javac -version
      script:
        - ./gradlew test
    #OpenJDK 8
    - language: java
      dist: trusty
      jdk: openjdk8
      before_script:
        - java -version
        - javac -version
      script:
        - ./gradlew test
      addons:
        apt:
          packages:
            - openjdk-8-jdk
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
           - $HOME/.gradle/caches/
           - $HOME/.gradle/wrapper/
     #Generating Pandoc documentation
    - language: r
      dist: trusty
      pandoc_version: 1.19.2.1
      install:
        - pandoc --version
      script:
        - if [ "${TRAVIS_BRANCH}" = "book" ]; then
              pandoc ./doc/ru.md --latex-engine=xelatex -o ru.pdf;
              pandoc ./doc/en.md --latex-engine=xelatex -o en.pdf;
              git clone --depth 1 -b gh-pages origin;
          fi;
