notifications:
  email: false
matrix:
  include:
    #OracleJDK 8
    - language: java
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_script:
        - java -version
        - javac -version
      script:
        - ./gradlew test
    #OpenJDK 8
    - language: java
      dist: trusty
      jdk: openjdk8
      before_script:
        - java -version
        - javac -version
      script:
        - ./gradlew test
      addons:
        apt:
          packages:
            - openjdk-8-jdk
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
           - $HOME/.gradle/caches/
           - $HOME/.gradle/wrapper/
     #Generating Pandoc documentation
    - language: r
      dist: trusty
      env:
        - secure: "ZKA5hC8vESWIpGraFB97MqYDyigzOzYW5cYVWT5e7MrO4cDipnYZtdS/4caTYGvbDmzcnYof2ea04Fxc2u0wFiy3JYz7YsX00PysDE80bTK1vMGaSZOI0Jl5ipwp7ivLlqGG2hBOS8kckEX0QzLlvLY6u+QJ7U0bYINGPlhDe+Vcgggw2Ihz0RiVioF+g6QKuMsZpsIQX3z8RBGJ+3MsZdVio8A8CZ8Asbs+6if+GuxsRFv9tFBc/WFHt1D/XRMIXuZEHSN1x2sEKmD/woHyMuzsVzQ4LLm2IF4NIOGLQkHt+g15JQT/mnBjec4MfW0P5x/UJeEq8+SCiXULLM7I7NVoKX/kRFve/2HYA/5XYDcQiqCfF4rHDx02D8CqNT5rLK2KKRve47nMefcZi0bc73aaCCRUaXaQYFJceTbMILsmCS3h5/FVH2V8EOpds12GwhiA86hOzBXRlUx31JQC+ZKuP4wJLVrduNehizQW6ZO2B5We/4toT10Jgd+pDHGdhcXmJStXpkZz2/vBd3YsKvnMhWTHBOIiySOr8wFzKRhXNHJwf46HZgZRbixTqwKCQ4J1/Qp+jqQqca2rTiErlzIxIf2HsR1m/x6An+YonrWYkxJ1eIMSNgC21ApXPLFS/QHSCX8P0fjb9MbDVrOBLozrpzNgOzHj0N34uKN+5Pc="
      branches:
        only:
        - book
      pandoc_version: 1.19.2.1
      install:
        - pandoc --version
        - tlmgr install xkeyval
      script:
        #create pdf
        - pandoc ./doc/ru.md --latex-engine=xelatex -o ru.pdf;
        - pandoc ./doc/en.md --latex-engine=xelatex -o en.pdf;

        #setup ssh
        - echo $pass | gpg --passphrase-fd 0 deploy_key.gpg
        - chmod 600 deploy_key
        - eval `ssh-agent -s`
        - ssh-add deploy_key

        #commit pdf
        - git fetch origin
        - git checkout gh-pages
        - git config user.name "$COMMIT_AUTHOR_EMAIL"
        - git config user.email "Travis CI"
        - git add -f ru.pdf en.pdf
        - git commit -m "Built book from {$SHA}."
        - git push -f "git@github.com:OpenSecreto/SigmaCoin.git" gh-pages

