/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ramil_HOME' at '28.10.16 22:32' with Gradle 3.1
 *
 * @author Ramil_HOME, @date 28.10.16 22:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
